source :rubygems

gem 'sinatra'
gem 'sass', "~> 3.2.0.alpha.101"
gem 'compass'
gem 'coffee-script'

gem "guard"
gem 'growl'
gem "rb-fsevent"

gem "guard-livereload"
gem "guard-coffeescript"
gem "guard-compass"
