# A sample Guardfile
# More info at https://github.com/guard/guard#readme

guard 'coffeescript', :input => 'coffeescripts', :output => 'public/javascripts/generated'

guard 'compass' do
  watch(/^views\/sass\/(.*)\.s[ac]ss/)
end

guard 'livereload' do
  watch(%r{views/.+\.(erb|haml|slim)})
  watch(%r{public/.+\.(css|js|html)})
end
